application:
  inputFilesDir: input
  processedFilesDir: processed
  outputFilesDir: output
  scheduler.interval: 10_000

mongodb:
  host: localhost
  port: 27017
  database.name: test
  collection.name: clients

logging:
  level:
    ROOT: INFO
    com.andersen: DEBUG